### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'phrase_mask'

### ISSUE THREAD

**Issue by nutsformers** [WadeYin9712/SentiBERT#3]
Hey WadeYin9712, absolutely love the work. During fine-tuning sstphrase, I can across the above error. I was looking for the error when I found you had used it in the Input features. While working with BERT, I haven't come across this masking. Does this have to do with the new module pytorch_pretrained_bert.modeling_new? Because that was also an error that I had to change to pytorch_pretrained_bert.modeling to import BertforPretraining. Could you help me out with this? Thanks in advance!

**Comment by WadeYin9712** [comment]
Hi, nutformers! Thanks a lot for your interest in our work! If you want to use BERT instead of SentiBERT, please just add one command line, '--para bert'. '--para' is designed for the two pretrained parameter options, 'sentibert' or 'bert'.

**Comment by WadeYin9712** [comment]
Hi Nutsformers, thanks a lot for your interest in our work! Actually modeling.py doesn't exist in our code. Perhaps this is the problem caused by enviroment paths. You might have another version of pytorch-pretrained-bert installed in your machine, and it might influence the execution of SentiBERT.

**Comment by WadeYin9712** [comment]
There might be a solution we mentioned in README. Perhaps you can try to run these commands:

export PYTHONPATH=$PYTHONPATH:XX/SentiBERT/pytorch_pretrained_bert
export PYTHONPATH=$PYTHONPATH:XX/SentiBERT/
export PYTHONPATH=$PYTHONPATH:XX/

The modeling_new.py will be added to enviromental path. 

I don't know if I understand your problem correctly or not. Let me know if you have any other problems! Thanks!

**Comment by nutsformers** [comment]
I would like to use sentibert as well. This is the code and error that i have recieved.
CUDA_VISIBLE_DEVICES=7 python3 finetune_on_pregenerated_sstphrase.py \
> --pregenerated_data /mnt/f/GitHub/SentiBERT/training_sstphrase \
> --bert_model bert-base-uncased \
> --do_lower_case \
> --output_dir /mnt/f/GitHub/SentiBERT/results/sstphrase_pretrain \
> --epochs 3
2020-09-08 18:19:27,261: device: cpu n_gpu: 0, distributed training: False, 16-bits training: False
2020-09-08 18:19:28,279: loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/dsekar/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084
2020-09-08 18:19:29,335: loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /home/dsekar/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
2020-09-08 18:19:29,346: extracting archive file /home/dsekar/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmpt_f7m187
2020-09-08 18:19:33,951: Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

2020-09-08 18:19:37,773: ***** Running training *****
2020-09-08 18:19:37,773:   Num examples = 25137
2020-09-08 18:19:37,774:   Batch size = 32
2020-09-08 18:19:37,774:   Num steps = 785
2020-09-08 18:19:39,555: Loading training examples for epoch 0
Training examples: 100%|███████████████████████████████████████████| 8379/8379 [01:01<00:00, 136.75it/s]
2020-09-08 18:20:49,578: Loading complete!
Epoch 0:   0%|                                                                  | 0/262 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "finetune_on_pregenerated_sstphrase.py", line 391, in <module>
    main()
  File "finetune_on_pregenerated_sstphrase.py", line 352, in main
    loss = model(input_ids=input_ids, token_type_ids=segment_ids, attention_mask=input_mask, phrase_mask=phrase_mask, masked_lm_labels=lm_label_ids, next_sentence_label=is_next, graph_label=graph_label, span=span, span_3=span_3)
  File "/home/dsekar/anaconda3/envs/sentibert/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'phrase_mask'

**Comment by WadeYin9712** [comment]
Can you try these commands?

export PYTHONPATH=$PYTHONPATH:XX/SentiBERT/pytorch_pretrained_bert
export PYTHONPATH=$PYTHONPATH:XX/SentiBERT/
export PYTHONPATH=$PYTHONPATH:XX/

**Comment by nutsformers** [comment]
There was a change in the path! Thank you for clarify. Although, each epoch is taking considerable amount of time. Could you let me know what was your initial time to run each epoch! Cheers!

**Comment by WadeYin9712** [comment]
Glad to hear from you! Actually it takes about 3mins each epoch with only one GPU card, which means the speed is fast at all. One of the reasons might be your GPU issues. We used NVIDIA GeForce GTX 1080 Ti cards. Perhaps you can try different sets of GPU or even an alternative server.
